Enhance factorial script with input check and syntax update
Added input validation and modernized arithmetic syntax.

diff --git a/dir1/g b/dir1/g
--- a/dir1/g
+++ b/dir1/g
@@ -2,11 +2,19 @@
 
 #!/bin/bash
 
+# 1. Protection: Ensure an argument was actually passed to the script
+if [ -z "$1" ]; then
+    echo "Error: Please provide a number. Usage: $0 <number>"
+    exit 1
+fi
+
 num=$1
 fact=1
 
-while [ $num -gt 1 ];do
-fact=`expr $fact \* $num`
-num=`expr $num - 1`
+# 2. Loop and calculate using modern arithmetic syntax
+while [ "$num" -gt 1 ]; do
+    fact=$((fact * num))
+    num=$((num - 1))
 done
+
 echo "fact of $1 is $fact"
